### ISSUE TITLE
Use other symbolic icon than eye

### ISSUE THREAD

**Issue by gregorni** [jorchube/monitorets#27] opened 2023-01-08 11:16 UTC
I think the button to the settings had better be a gear, three-dot or hamburger menu. An eye doesn't really fit I think.

**Comment by jorchube** [comment] 2023-01-08 12:00
Hi!

I don't really know what eye are you talking about. I am inclined to think that you have installed a custom iconset. This is the preferences button in the stable branch currently:

![image](https://user-images.githubusercontent.com/1174736/211194874-b651224e-a2ac-48e2-a369-338921f6bf82.png)

**Comment by gregorni** [comment] 2023-01-08 13:28
This is what it looks like with me:

![Screenshot_2023-01-08_14-24-05](https://user-images.githubusercontent.com/119804311/211198591-f76178b4-1bba-47aa-bb11-e001b81170c1.png)

Again, this might be my distro messing up.

**Comment by gregorni** [comment] 2023-01-08 13:32
I just noticed something: When running the app with Builder, it uses a hamburger menu and creates seperate windows for settings, about and hints, eliminating both of my issues. Is that intentional?

**Comment by jorchube** [comment] 2023-01-08 13:43
> I just noticed something: When running the app with Builder, it uses a hamburger menu and creates seperate windows for settings, about and hints, eliminating both of my issues. Is that intentional?

If you have build the master branch then you are looking at changes that will be included in the next release. Keep the secret! :p

**Comment by jorchube** [comment] 2023-01-11 08:14
Closing this as it is not a bug and also no longer applies since version 0.7.0.

**Closed by jorchube** 2023-01-11 08:14 UTC
